/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.KhachHangBLL;
import Common.BindingTableFromQLKH;
import BLL.GiftBLL;
import DTO.GiftDTO;
import Common.BindingTableFromDoiQuaTL;
import DTO.KhachHangDTO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author DaoLam
 */
public class fDoiQua extends javax.swing.JPanel {
    /**
     * Creates new form fTaoDonHang
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public fDoiQua() throws UnsupportedLookAndFeelException {
        initComponents();
        bindingTableFormQLKH.bindingtbQLKH(jTableKH, KhachHangBLL.getAll());
        bindingTableFormDoiQuaTL.bindingtbQua(jTableQua, GiftBLL.getAll());
        jTextTenKH.setEditable(false);
        jTextMaKH.setEditable(false);
        jTextDTL.setEditable(false);
        jTextMaQua.setEnabled(false);
        jTextTenQua.setEnabled(false);
        jTextMucDiem.setEnabled(false);
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(null, "Loi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMaKH = new javax.swing.JLabel();
        jTextMaKH = new javax.swing.JTextField();
        jTenKH = new javax.swing.JLabel();
        jTextTenKH = new javax.swing.JTextField();
        jButtonTimKiemKH = new javax.swing.JButton();
        jTextDTL = new javax.swing.JTextField();
        jDTL = new javax.swing.JLabel();
        jTextTimKH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKH = new javax.swing.JTable();
        jButtonDoiQua = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableQua = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jMaQua = new javax.swing.JLabel();
        jTextMaQua = new javax.swing.JTextField();
        jTenQua = new javax.swing.JLabel();
        jTextTenQua = new javax.swing.JTextField();
        jButtonTimKiem1 = new javax.swing.JButton();
        jTextMucDiem = new javax.swing.JTextField();
        jMucDiem = new javax.swing.JLabel();
        ButtonThem = new javax.swing.JButton();
        ButtonSua = new javax.swing.JButton();
        ButtonLuu = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        jTextTimMD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMaKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMaKH.setForeground(new java.awt.Color(102, 102, 102));
        jMaKH.setText("Mã khách hàng");

        jTextMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaKHActionPerformed(evt);
            }
        });

        jTenKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTenKH.setForeground(new java.awt.Color(102, 102, 102));
        jTenKH.setText("Tên khách hàng");

        jTextTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTenKHActionPerformed(evt);
            }
        });

        jButtonTimKiemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_Citycons_magnify_1342938.png"))); // NOI18N
        jButtonTimKiemKH.setText("Tìm kiếm");
        jButtonTimKiemKH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTimKiemKH.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonTimKiemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemKHActionPerformed(evt);
            }
        });

        jDTL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jDTL.setForeground(new java.awt.Color(102, 102, 102));
        jDTL.setText("Điểm tích lũy");

        jTextTimKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTimKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTenKH)
                            .addComponent(jMaKH))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTenKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonTimKiemKH)
                            .addComponent(jDTL))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDTL, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMaKH)
                    .addComponent(jTextMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTenKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDTL)
                    .addComponent(jTextDTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTimKiemKH)
                    .addComponent(jTextTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/shopping-bag (2).png"))); // NOI18N
        jLabel1.setText("Đổi quà tích lũy");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Thông tin khách hàng");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));

        jTableKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKH);

        jButtonDoiQua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonDoiQua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/restaurant-membership-card-tool.png"))); // NOI18N
        jButtonDoiQua.setText("Đổi quà");
        jButtonDoiQua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonDoiQua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonDoiQua.setPreferredSize(new java.awt.Dimension(101, 41));
        jButtonDoiQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoiQuaActionPerformed(evt);
            }
        });

        jTableQua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableQua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQuaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableQua);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMaQua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMaQua.setForeground(new java.awt.Color(102, 102, 102));
        jMaQua.setText("Mã quà");

        jTextMaQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaQuaActionPerformed(evt);
            }
        });

        jTenQua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTenQua.setForeground(new java.awt.Color(102, 102, 102));
        jTenQua.setText("Tên quà");

        jTextTenQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTenQuaActionPerformed(evt);
            }
        });

        jButtonTimKiem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_Citycons_magnify_1342938.png"))); // NOI18N
        jButtonTimKiem1.setText("Tìm kiếm");
        jButtonTimKiem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTimKiem1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiem1ActionPerformed(evt);
            }
        });

        jMucDiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMucDiem.setForeground(new java.awt.Color(102, 102, 102));
        jMucDiem.setText("Mức điểm");

        ButtonThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_sign-add_299068 (1).png"))); // NOI18N
        ButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThemActionPerformed(evt);
            }
        });

        ButtonSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_pencil_1055013 (1).png"))); // NOI18N
        ButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSuaActionPerformed(evt);
            }
        });

        ButtonLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_floppy_285657 (1).png"))); // NOI18N
        ButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLuuActionPerformed(evt);
            }
        });

        ButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_Delete_1493279.png"))); // NOI18N
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ButtonThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonLuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(ButtonCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMaQua, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTenQua, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextTenQua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextMaQua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jMucDiem)
                                .addGap(18, 18, 18)
                                .addComponent(jTextMucDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonTimKiem1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextTimMD, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMaQua)
                    .addComponent(jTextMaQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTenQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTenQua))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMucDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMucDiem))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTimKiem1)
                    .addComponent(jTextTimMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCancel)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonThem)
                        .addComponent(ButtonSua)
                        .addComponent(ButtonLuu)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Thông tin quà");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jButtonDoiQua, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonDoiQua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaKHActionPerformed

    private void jTextTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTenKHActionPerformed

    private void jButtonTimKiemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemKHActionPerformed
        bindingTableFormQLKH.bindingtbQLKH(jTableKH, KhachHangBLL.searchByName(jTextTimKH.getText()));
    }//GEN-LAST:event_jButtonTimKiemKHActionPerformed

    private void jTableKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKHMouseClicked
        {
            int row = jTableKH.getSelectedRow();
            jTextMaKH.setText(jTableKH.getValueAt(row, 0).toString());
            jTextTenKH.setText(jTableKH.getValueAt(row, 1).toString());
            jTextDTL.setText(jTableKH.getValueAt(row, 6).toString());
        }
    }//GEN-LAST:event_jTableKHMouseClicked

    private void jButtonDoiQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoiQuaActionPerformed
        flag =3;
    }//GEN-LAST:event_jButtonDoiQuaActionPerformed

    private void jTableQuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQuaMouseClicked
        int row = jTableQua.getSelectedRow();
        jTextMaQua.setText(jTableQua.getValueAt(row, 0).toString());
        jTextTenQua.setText(jTableQua.getValueAt(row, 1).toString());
        jTextMucDiem.setText(jTableQua.getValueAt(row, 2).toString());
    }//GEN-LAST:event_jTableQuaMouseClicked

    private void jTextMaQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMaQuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaQuaActionPerformed

    private void jTextTenQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTenQuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTenQuaActionPerformed

    private void jButtonTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiem1ActionPerformed
        bindingTableFormDoiQuaTL.bindingtbQua(jTableQua, GiftBLL.searchByName(jTextTimMD.getText()));
    }//GEN-LAST:event_jButtonTimKiem1ActionPerformed

    private void ButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThemActionPerformed
        controlTxb(true);
        clearTxb();
        jTextMaQua.setText(GiftBLL.generateId().toString());
        flag = 1;
    }//GEN-LAST:event_ButtonThemActionPerformed

    private void ButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSuaActionPerformed
        controlTxb(true);
        flag = 2;
    }//GEN-LAST:event_ButtonSuaActionPerformed

    private void ButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLuuActionPerformed
        GiftDTO Gift = new GiftDTO();
        KhachHangDTO KH = new KhachHangDTO();
        bindingGift(Gift);
        bindingKH(KH);
        /*if (KhachHangBLL.checkValid(KH)) {
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }*/

        switch (flag) {
            case 1: {
                if (GiftBLL.insertGift(Gift)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }

                break;
            }

            case 2: {
                if (GiftBLL.updateGift(Gift)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }

                break;
            }
            case 3:{
                Integer A = 0;
                A = Integer.parseInt(jTextDTL.getText().toString()) - Integer.parseInt(jMucDiem.getText().toString());
                if(A<0)
                {
                    JOptionPane.showMessageDialog(this, "Điểm tích lũy của khách hàng không đủ");
                }
                else{
                    if(KhachHangBLL.updateDTL(KH))
                    {
                        JOptionPane.showMessageDialog(this, "Cập nhật thành công");}
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                    }
                }
                break;
            }

            default:
            break;
        }

        bindingTableFormDoiQuaTL.bindingtbQua(jTableQua, GiftBLL.getAll());
        controlTxb(false);
    }//GEN-LAST:event_ButtonLuuActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        clearTxb();
        controlTxb(false);
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void jTextTimKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTimKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTimKHActionPerformed
     
     private void controlTxb(boolean control) {
        ButtonLuu.setEnabled(control);
        ButtonSua.setEnabled(!control);
        ButtonThem.setEnabled(!control);
        jTextMaQua.setEnabled(control);
        jTextTenQua.setEnabled(control);
        jTextMucDiem.setEnabled(control);
    }

    public void clearTxb() {
        jTextMaQua.setText("");
        jTextTenQua.setText("");
        jTextMucDiem.setText("");
    }

    public boolean bindingGift(GiftDTO Gift) {
        try{
            Gift.setMaQua(Integer.parseInt(jTextMaQua.getText()));
            Gift.SetTenQua(jTextTenQua.getText());
            Gift.setMucDiem(Integer.parseInt(jTextMucDiem.getText()));
        }
        catch(NumberFormatException e)
        {
            return false;
        }
        return true;
    
    
    }
    public boolean bindingKH(KhachHangDTO KH){
        try{
            KH.SetMaKH(Integer.parseInt(jTextMaQua.getText()));
            KH.SetHoten(jTextTenKH.getText());
            KH.SetDiemTichLuy(Integer.parseInt(jTextMucDiem.getText()));
        }
        catch(NumberFormatException e)
        {
            return false;
        }
        return true;
    }
    private int flag = 0;
    private KhachHangBLL KhachHangBLL = new KhachHangBLL();
    private GiftBLL GiftBLL = new GiftBLL();
    private Common.BindingTableFromQLKH bindingTableFormQLKH = new BindingTableFromQLKH();
    private Common.BindingTableFromDoiQuaTL bindingTableFormDoiQuaTL = new BindingTableFromDoiQuaTL();
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonLuu;
    private javax.swing.JButton ButtonSua;
    private javax.swing.JButton ButtonThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButtonDoiQua;
    private javax.swing.JButton jButtonTimKiem1;
    private javax.swing.JButton jButtonTimKiemKH;
    private javax.swing.JLabel jDTL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMaKH;
    private javax.swing.JLabel jMaQua;
    private javax.swing.JLabel jMucDiem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableKH;
    private javax.swing.JTable jTableQua;
    private javax.swing.JLabel jTenKH;
    private javax.swing.JLabel jTenQua;
    private javax.swing.JTextField jTextDTL;
    private javax.swing.JTextField jTextMaKH;
    private javax.swing.JTextField jTextMaQua;
    private javax.swing.JTextField jTextMucDiem;
    private javax.swing.JTextField jTextTenKH;
    private javax.swing.JTextField jTextTenQua;
    private javax.swing.JTextField jTextTimKH;
    private javax.swing.JTextField jTextTimMD;
    // End of variables declaration//GEN-END:variables
}
