/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.CongTyBLL;
import BLL.NhanVienBLL;
import Common.BindingTableFormQLCongTy;
import DTO.CongTyDTO;
import DTO.NhanVienDTO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.util.ArrayList;

/**
 *
 * @author HUY
 */
public class fQLCTy extends javax.swing.JPanel {

    /**
     * Creates new form fQLNV
     */
    public fQLCTy() {
        initComponents();
        controlTxb(false);
        ArrayList listCongty = new ArrayList();
        if (!congTyBll.getAll(listCongty)) {
            JOptionPane.showMessageDialog(this, "Can't load table Cong ty");
        } else {
            bindingTableFormQLCongTy.bindingTbleCty(tblCty, listCongty);
        }
        
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(null, "Loi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMaNV = new javax.swing.JLabel();
        txbMaCTy = new javax.swing.JTextField();
        jTenNV = new javax.swing.JLabel();
        jSDT = new javax.swing.JLabel();
        txbSDT = new javax.swing.JTextField();
        txbDiaChi = new javax.swing.JTextField();
        jDiachi = new javax.swing.JLabel();
        txbTenCty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCty = new javax.swing.JTable();
        jMNVTK = new javax.swing.JLabel();
        txbSearchCty = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();
        jButtonLuu = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(875, 626));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMaNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMaNV.setForeground(new java.awt.Color(102, 102, 102));
        jMaNV.setText("Mã công ty");

        txbMaCTy.setEditable(false);
        txbMaCTy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbMaCTyActionPerformed(evt);
            }
        });

        jTenNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTenNV.setForeground(new java.awt.Color(102, 102, 102));
        jTenNV.setText("Tên công ty");

        jSDT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSDT.setForeground(new java.awt.Color(102, 102, 102));
        jSDT.setText("SĐT");

        jDiachi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jDiachi.setForeground(new java.awt.Color(102, 102, 102));
        jDiachi.setText("Địa chỉ");

        txbTenCty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbTenCtyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDiachi)
                            .addComponent(jSDT)
                            .addComponent(jMaNV))
                        .addGap(4, 4, 4))
                    .addComponent(jTenNV, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txbMaCTy, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txbDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(txbSDT)
                        .addComponent(txbTenCty)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMaNV)
                    .addComponent(txbMaCTy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbTenCty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTenNV))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSDT)
                    .addComponent(txbSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDiachi))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/business_people_01.png"))); // NOI18N
        jLabel1.setText("Quản Lý Công Ty");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));

        tblCty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCtyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCty);

        jMNVTK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMNVTK.setForeground(new java.awt.Color(102, 102, 102));
        jMNVTK.setText("Tên công ty");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_Citycons_magnify_1342938.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_sign-add_299068 (1).png"))); // NOI18N
        jButtonThem.setText("Thêm");
        jButtonThem.setToolTipText("");
        jButtonThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonThem.setPreferredSize(new java.awt.Dimension(101, 41));
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_pencil_1055013 (1).png"))); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonSua.setMaximumSize(new java.awt.Dimension(95, 41));
        jButtonSua.setMinimumSize(new java.awt.Dimension(95, 41));
        jButtonSua.setPreferredSize(new java.awt.Dimension(101, 41));
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_Delete_1493279.png"))); // NOI18N
        jButtonHuy.setText("Hủy");
        jButtonHuy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonHuy.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonHuy.setPreferredSize(new java.awt.Dimension(101, 41));
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });

        jButtonLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_floppy_285657 (1).png"))); // NOI18N
        jButtonLuu.setText("Lưu");
        jButtonLuu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonLuu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonLuu.setPreferredSize(new java.awt.Dimension(101, 41));
        jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jMNVTK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txbSearchCty, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMNVTK)
                            .addComponent(txbSearchCty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txbMaCTyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbMaCTyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbMaCTyActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        controlTxb(true);
        clearTxb();
        txbMaCTy.setText(congTyBll.genarateId().toString());
        flag = 1;
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
         controlTxb(true);
         flag = 2;
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuuActionPerformed
        CongTyDTO congTy = new CongTyDTO();
        if (!bindingCty(congTy)) {
            JOptionPane.showMessageDialog(this, "Thông tin nhập không đúng quy định");
            return;
        }
        /*if (NhanVienBLL.checkValid(NV)) {
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }*/

        switch (flag) {
            case 1: {
                if (congTyBll.insertCty(congTy)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }

                break;
            }

            case 2: {
                if (congTyBll.updateCty(congTy)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }

                break;
            }
            
            default:
                break;
        }

        ArrayList<CongTyDTO> listCongTy = new ArrayList<>();
        if (!congTyBll.getAll(listCongTy)) {
            JOptionPane.showMessageDialog(this, "Cant load table cong ty");
        }
        
       bindingTableFormQLCongTy.bindingTbleCty(tblCty, listCongTy);
        controlTxb(false);
    }//GEN-LAST:event_jButtonLuuActionPerformed

    private void txbTenCtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbTenCtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbTenCtyActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        clearTxb();
        controlTxb(false);
    }//GEN-LAST:event_jButtonHuyActionPerformed
    //Load vao Textbox
    private void tblCtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCtyMouseClicked
        {
            controlTxb(false);
            int row = tblCty.getSelectedRow();
            txbMaCTy.setText(tblCty.getValueAt(row, 0).toString());
            txbTenCty.setText(tblCty.getValueAt(row, 1).toString());
            txbDiaChi.setText(tblCty.getValueAt(row, 2).toString());
            txbSDT.setText(tblCty.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_tblCtyMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        ArrayList<CongTyDTO> listCongTy = new ArrayList<>();
        if (!congTyBll.searchCtyByName(txbSearchCty.getText(), listCongTy)) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm");
        } else {
            bindingTableFormQLCongTy.bindingTbleCty(tblCty, listCongTy);
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    private void controlTxb(boolean control) {
        jButtonLuu.setEnabled(control);
        jButtonSua.setEnabled(!control);
        jButtonThem.setEnabled(!control);
        txbTenCty.setEnabled(control);
        txbSDT.setEnabled(control);
        txbDiaChi.setEnabled(control);
    }

    public void clearTxb() {
        txbMaCTy.setText("");
        txbTenCty.setText("");
        txbSDT.setText("");
        txbDiaChi.setText("");
        //jTextDTL.setText("");
    }

    public boolean bindingCty(CongTyDTO cty) {
        try {
            cty.setMaCty(Integer.parseInt(txbMaCTy.getText()));
            cty.setTenCty(txbTenCty.getText());
            cty.setDiaChi(txbDiaChi.getText());
            String sdt = txbSDT.getText();
            Integer.parseInt(sdt);
            if (sdt.length() <  8 || sdt.length() > 10) {
                return false;
            }
            cty.setSDT(txbSDT.getText());
        } catch (NumberFormatException e) {
            return false;
        }
        
        return true;
    }
    
    private int flag = 0;
    private CongTyBLL congTyBll = new CongTyBLL();
    private Common.BindingTableFormQLCongTy bindingTableFormQLCongTy = new BindingTableFormQLCongTy();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JLabel jDiachi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jMNVTK;
    private javax.swing.JLabel jMaNV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jSDT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTenNV;
    private javax.swing.JTable tblCty;
    private javax.swing.JTextField txbDiaChi;
    private javax.swing.JTextField txbMaCTy;
    private javax.swing.JTextField txbSDT;
    private javax.swing.JTextField txbSearchCty;
    private javax.swing.JTextField txbTenCty;
    // End of variables declaration//GEN-END:variables
}
