/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.NhanVienBLL;
import Common.BindingTableFromQLNV;
import DTO.NhanVienDTO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.util.Date;
import java.text.SimpleDateFormat;  
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.ParseException;
import java.util.Calendar;

/**
 *
 * @author HUY
 */
public class fQLNV extends javax.swing.JPanel {

    /**
     * Creates new form fQLNV
     */
    public fQLNV() {
        initComponents();
        bindingTableFormQLNV.bindingtbQLNV(jTableNV, NhanVienBLL.getAll());
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(null, "Loi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMaNV = new javax.swing.JLabel();
        jTextMaNV = new javax.swing.JTextField();
        jTenNV = new javax.swing.JLabel();
        jTextCMND = new javax.swing.JTextField();
        jSDT = new javax.swing.JLabel();
        jTextSDT = new javax.swing.JTextField();
        jNgaysinh = new javax.swing.JLabel();
        jTextDiaChi = new javax.swing.JTextField();
        jDiachi = new javax.swing.JLabel();
        jTextTenNV = new javax.swing.JTextField();
        jCMND = new javax.swing.JLabel();
        jNgaySinhpick = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNV = new javax.swing.JTable();
        jButtonHuy = new javax.swing.JButton();
        jMNVTK = new javax.swing.JLabel();
        jTextTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jButtonSaThai = new javax.swing.JButton();
        jButtonLuu = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(875, 626));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMaNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMaNV.setForeground(new java.awt.Color(102, 102, 102));
        jMaNV.setText("Mã nhân viên");

        jTextMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaNVActionPerformed(evt);
            }
        });

        jTenNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTenNV.setForeground(new java.awt.Color(102, 102, 102));
        jTenNV.setText("Tên nhân viên");

        jTextCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCMNDActionPerformed(evt);
            }
        });

        jSDT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSDT.setForeground(new java.awt.Color(102, 102, 102));
        jSDT.setText("SĐT");

        jNgaysinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jNgaysinh.setForeground(new java.awt.Color(102, 102, 102));
        jNgaysinh.setText("Ngày sinh");

        jDiachi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jDiachi.setForeground(new java.awt.Color(102, 102, 102));
        jDiachi.setText("Địa chỉ");

        jTextTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTenNVActionPerformed(evt);
            }
        });

        jCMND.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCMND.setForeground(new java.awt.Color(102, 102, 102));
        jCMND.setText("CMND");

        jNgaySinhpick.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jMaNV)
                        .addGap(21, 21, 21)
                        .addComponent(jTextMaNV))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTenNV)
                        .addGap(18, 18, 18)
                        .addComponent(jTextTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCMND)
                    .addComponent(jSDT))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jNgaysinh))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDiachi)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNgaySinhpick, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMaNV)
                    .addComponent(jTextMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDiachi)
                    .addComponent(jTextSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSDT))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTenNV)
                        .addComponent(jTextCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCMND)
                        .addComponent(jTextTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jNgaysinh))
                    .addComponent(jNgaySinhpick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/business_people_01.png"))); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Thông tin nhân viên");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));

        jButtonThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_sign-add_299068 (1).png"))); // NOI18N
        jButtonThem.setText("Thêm");
        jButtonThem.setToolTipText("");
        jButtonThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonThem.setPreferredSize(new java.awt.Dimension(101, 41));
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_pencil_1055013 (1).png"))); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonSua.setMaximumSize(new java.awt.Dimension(95, 41));
        jButtonSua.setMinimumSize(new java.awt.Dimension(95, 41));
        jButtonSua.setPreferredSize(new java.awt.Dimension(101, 41));
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jTableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNV);

        jButtonHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_Delete_1493279.png"))); // NOI18N
        jButtonHuy.setText("Hủy");
        jButtonHuy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonHuy.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonHuy.setPreferredSize(new java.awt.Dimension(101, 41));
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });

        jMNVTK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMNVTK.setForeground(new java.awt.Color(102, 102, 102));
        jMNVTK.setText("Nhân Viên");

        jButtonTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_Citycons_magnify_1342938.png"))); // NOI18N
        jButtonTimKiem.setText("Tìm kiếm");
        jButtonTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        jButtonSaThai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bt_remove (2).png"))); // NOI18N
        jButtonSaThai.setText("Sa thải");
        jButtonSaThai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSaThai.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonSaThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaThaiActionPerformed(evt);
            }
        });

        jButtonLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_floppy_285657 (1).png"))); // NOI18N
        jButtonLuu.setText("Lưu");
        jButtonLuu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonLuu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonLuu.setPreferredSize(new java.awt.Dimension(101, 41));
        jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonTimKiem))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSaThai, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jMNVTK)
                                .addGap(18, 18, 18)
                                .addComponent(jTextTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMNVTK)
                    .addComponent(jTextTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaThai)
                    .addComponent(jButtonLuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTimKiem)
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCMNDActionPerformed

    private void jTextMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaNVActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        controlTxb(true);
        clearTxb();
        jTextMaNV.setText(NhanVienBLL.generateId().toString());
        flag = 1;
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
         controlTxb(true);
         flag = 2;
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuuActionPerformed
        NhanVienDTO NV = new NhanVienDTO();
        bindingNV(NV);
        
        /*if (NhanVienBLL.checkValid(NV)) {
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }*/

        switch (flag) {
            case 1: {
                if (NhanVienBLL.insertNV(NV)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }

                break;
            }

            case 2: {
                if (NhanVienBLL.updateNV(NV)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                }

                break;
            }
            case 3:{
            try {
                bindingSathaiNV(NV);
                if(NhanVienBLL.sathaiNV(NV)){
                    JOptionPane.showMessageDialog(this, "Sa thải thành công");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Sa thải thất bại");
                }                
            } catch (ParseException ex) {
                Logger.getLogger(fQLNV.class.getName()).log(Level.SEVERE, null, ex);
            }
            }

            default:
                break;
        }

        bindingTableFormQLNV.bindingtbQLNV(jTableNV, NhanVienBLL.getAll());
        controlTxb(false);
    }//GEN-LAST:event_jButtonLuuActionPerformed

    private void jTextTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTenNVActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        clearTxb();
        controlTxb(false);
    }//GEN-LAST:event_jButtonHuyActionPerformed
    //Load vao Textbox
    private void jTableNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNVMouseClicked
        {
            try {
                int row = jTableNV.getSelectedRow();
                jTextMaNV.setText(jTableNV.getValueAt(row, 0).toString());
                jTextTenNV.setText(jTableNV.getValueAt(row, 1).toString());
                jTextSDT.setText(jTableNV.getValueAt(row, 2).toString());
                jTextCMND.setText(jTableNV.getValueAt(row, 4).toString());
                jTextDiaChi.setText(jTableNV.getValueAt(row, 3).toString());
                String dateStr = jTableNV.getValueAt(row,5).toString();
                SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
                Date date = format1.parse(dateStr);
                Calendar cal = Calendar.getInstance();
                cal.setTime(date);
                jNgaySinhpick.setSelectedDate(cal);
                controlTxb(false);
            } catch (ParseException ex) {
                Logger.getLogger(fQLNV.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_jTableNVMouseClicked

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        bindingTableFormQLNV.bindingtbQLNV(jTableNV, NhanVienBLL.searchByName(jTextTimKiem.getText()));
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonSaThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaThaiActionPerformed
        flag =3;
        controlTxb(true);
    }//GEN-LAST:event_jButtonSaThaiActionPerformed
    private void controlTxb(boolean control) {
        jButtonLuu.setEnabled(control);
        jButtonSaThai.setEnabled(!control);
        jButtonSua.setEnabled(!control);
        jButtonThem.setEnabled(!control);
        jTextMaNV.setEnabled(control);
        jTextTenNV.setEnabled(control);
        jTextSDT.setEnabled(control);
        jTextDiaChi.setEnabled(control);
        jTextCMND.setEnabled(control);
        jNgaySinhpick.setEnabled(control);
    }

    public void clearTxb() {
        jTextMaNV.setText("");
        jTextTenNV.setText("");
        jTextSDT.setText("");
        jTextDiaChi.setText("");
        jTextCMND.setText("");
        //jTextDTL.setText("");
    }
    public boolean bindingSathaiNV(NhanVienDTO NV) throws ParseException
    {
        try{
            NV.Setdeleted(true);
            NV.SetMaNV(Integer.parseInt(jTextMaNV.getText()));
            NV.SetHoten(jTextTenNV.getText());
            NV.SetSDT(jTextSDT.getText());
            NV.SetDiaChi(jTextDiaChi.getText());
            NV.SetCMND(jTextCMND.getText());
            Calendar cal ;
            cal = jNgaySinhpick.getSelectedDate();
            Date datefm = cal.getTime();
            NV.SetNgaySinh(datefm);
        }
        catch(NumberFormatException e)
        {
            return false;
        }
        return true;
    }
    public boolean bindingNV(NhanVienDTO NV) {
        try{
            NV.SetMaNV(Integer.parseInt(jTextMaNV.getText()));
            NV.SetHoten(jTextTenNV.getText());
            NV.SetSDT(jTextSDT.getText());
            NV.SetDiaChi(jTextDiaChi.getText());
            NV.SetCMND(jTextCMND.getText());
            Calendar cal ;
            cal = jNgaySinhpick.getSelectedDate();
            Date datefm = cal.getTime();
            NV.SetNgaySinh(datefm);
        }
        catch(NumberFormatException e)
        {
            return false;
        }
        return true;
    }
    private int flag = 0;
    private NhanVienBLL NhanVienBLL = new NhanVienBLL();
    private Common.BindingTableFromQLNV bindingTableFormQLNV = new BindingTableFromQLNV();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JButton jButtonSaThai;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JLabel jCMND;
    private javax.swing.JLabel jDiachi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jMNVTK;
    private javax.swing.JLabel jMaNV;
    private datechooser.beans.DateChooserCombo jNgaySinhpick;
    private javax.swing.JLabel jNgaysinh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jSDT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNV;
    private javax.swing.JLabel jTenNV;
    private javax.swing.JTextField jTextCMND;
    private javax.swing.JTextField jTextDiaChi;
    private javax.swing.JTextField jTextMaNV;
    private javax.swing.JTextField jTextSDT;
    private javax.swing.JTextField jTextTenNV;
    private javax.swing.JTextField jTextTimKiem;
    // End of variables declaration//GEN-END:variables
}
